### ISSUE TITLE
Possible corona-virus in the code?

### ISSUE THREAD

**Issue by ejhusom** [steinnhauser/IN4200#1]
I forgot to wash my hands before I opened this repo, so might have infected the code with COVID-19. I have no symptoms myself, but I may be a carrier of the virus anyways. Just wanted to give you a heads up, in case it turns up while debugging.

**Comment by steinnhauser** [comment]
See to attached file for good rules-of-thumb on how to prepare yourself before entering repo's. Debugging is not necessary yet though I'll let you know in about two weeks. Stay safe!
![wash_ye_hands_ye_detty_pig](https://user-images.githubusercontent.com/42544980/77225437-e6214e00-6b66-11ea-8afd-e5124d935850.jpg)
